
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[sp_process_asset_ratings_under_meter]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[sp_process_asset_ratings_under_meter]
GO

CREATE PROCEDURE dbo.sp_process_asset_ratings_under_meter
	-- Required Parameters
	@meterId  int = NULL
AS


SELECT 
	BREAKDOWN.ID,
	BREAKDOWN.NUMBER,
	BREAKDOWN.NAME,
	COALESCE ( SUM( BREAKDOWN.SUB_BURNERS + BREAKDOWN.EP_RATED_MMBTU), BREAKDOWN.EP_RATED_MMBTU) AS RATING
FROM (
	SELECT  A.ID, 
		A.NUMBER,
		A.NAME,
		AA.EP_RATED_MMBTU, 
		SUM(SUB_AA.EP_RATED_MMBTU) AS SUB_BURNERS
	 FROM ENV_ASSET AS A
	 LEFT JOIN ENV_ASSET_TYPE AS ATYPE ON ATYPE.ASSET_ID = A.ID
	  AND ATYPE.ASSET_TYPE_CD in ( 1,2 )--natural gas assets
	 LEFT JOIN ENV_ASSET_ATTR AS AA ON AA.ASSET_ID = A.ID
	 LEFT JOIN ENV_ASSET AS SUB_A ON SUB_A.PARENT_ASSET_ID = A.ID
	 LEFT JOIN ENV_ASSET_ATTR AS SUB_AA ON SUB_AA.ASSET_ID = SUB_A.ID
	 WHERE A.BELONGS_TO_METER = @meterId
	 AND A.STATUS_CD = 1 AND A.PROCESS = 1 --active process assets
       GROUP BY A.ID, A.NUMBER, A.NAME, AA.EP_RATED_MMBTU
) AS BREAKDOWN 
GROUP BY BREAKDOWN.ID, BREAKDOWN.NUMBER, BREAKDOWN.NAME, BREAKDOWN.SUB_BURNERS, BREAKDOWN.EP_RATED_MMBTU
ORDER BY BREAKDOWN.NUMBER 
	
	GO

