
ALTER TABLE ENV_SCC_INFO
ADD COLUMN 	
	[MAJ_INDUSTRIAL_GROUP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
	
ALTER TABLE ENV_SCC_INFO
ADD COLUMN 	
	[RAW_MATERIAL] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
	
ALTER TABLE ENV_SCC_INFO
ADD COLUMN 	
	[EMITTING_PROCESS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
