
INSERT INTO ENV_SCC_INFO_LIBRARY (SCC_NUMBER, SCC_DESCRIPTION, MAJ_INDUSTRIAL_GROUP, RAW_MATERIAL, EMITTING_PROCESS, CREATE_TS, UPDATE_TS, UPDATE_USER_ID) 
SELECT SCC_NUMBER, SCC_DESCRIPTION, MAJ_INDUSTRIAL_GROUP, RAW_MATERIAL, EMITTING_PROCESS, CREATE_TS, UPDATE_TS, UPDATE_USER_ID FROM ENV_SCC_INFO