select * from ENV_SOURCE where ID in (
SELECT SCC.SOURCE_ID
	FROM ENV_ASSET_SOURCE AS ASSO 
		LEFT JOIN ENV_ASSET AS ASSET --asset equal to given asset id
		ON ASSET.ID = ASSO.ASSET_ID
		LEFT JOIN ENV_SOURCE_SCC_INFO AS SCC--sources for this scc
		 ON ASSO.SOURCE_ID = SCC.SOURCE_ID
		 AND ASSO.ASSET_ID = 16
		 AND ASSO.STATUS_CD = 1
	--WHERE SCC.SCC_INFO_ID = 9
	)