

/****** Object:  Index [ENV_SOURCE_SUBSTANCE_manymany]    Script Date: 03/27/2013 11:54:09 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ENV_SOURCE_SUBSTANCE]') AND name = N'ENV_SOURCE_SUBSTANCE_manymany')
DROP INDEX [ENV_SOURCE_SUBSTANCE_manymany] ON [dbo].[ENV_SOURCE_SUBSTANCE] WITH ( ONLINE = OFF )
GO



/****** Object:  Index [ENV_SOURCE_SUBSTANCE_manymany]    Script Date: 03/27/2013 11:54:09 ******/
CREATE NONCLUSTERED INDEX [ENV_SOURCE_SUBSTANCE_manymany] ON [dbo].[ENV_SOURCE_SUBSTANCE] 
(
	[SOURCE_ID] ASC,
	[SUBSTANCE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


