

/****** Object:  Index [ENV_ASSET_EMITTED_SUBSTANCE_TYPE_ASSET_ID]    Script Date: 03/27/2013 11:30:14 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ENV_ASSET_EMITTED_SUBSTANCE_TYPE]') AND name = N'ENV_ASSET_EMITTED_SUBSTANCE_TYPE_ASSET_ID')
DROP INDEX [ENV_ASSET_EMITTED_SUBSTANCE_TYPE_ASSET_ID] ON [dbo].[ENV_ASSET_EMITTED_SUBSTANCE_TYPE] WITH ( ONLINE = OFF )
GO



/****** Object:  Index [ENV_ASSET_EMITTED_SUBSTANCE_TYPE_ASSET_ID]    Script Date: 03/27/2013 11:30:14 ******/
CREATE NONCLUSTERED INDEX [ENV_ASSET_EMITTED_SUBSTANCE_TYPE_ASSET_ID] ON [dbo].[ENV_ASSET_EMITTED_SUBSTANCE_TYPE] 
(
	[ASSET_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


