

/****** Object:  Index [ENV_SOURCE_SCC_INFO_manymany]    Script Date: 03/27/2013 11:53:20 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ENV_SOURCE_SCC_INFO]') AND name = N'ENV_SOURCE_SCC_INFO_manymany')
DROP INDEX [ENV_SOURCE_SCC_INFO_manymany] ON [dbo].[ENV_SOURCE_SCC_INFO] WITH ( ONLINE = OFF )
GO



/****** Object:  Index [ENV_SOURCE_SCC_INFO_manymany]    Script Date: 03/27/2013 11:53:20 ******/
CREATE NONCLUSTERED INDEX [ENV_SOURCE_SCC_INFO_manymany] ON [dbo].[ENV_SOURCE_SCC_INFO] 
(
	[SOURCE_ID] ASC,
	[SCC_INFO_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


