

/****** Object:  Index [IX_ASSET_SOURCE_ID]    Script Date: 03/01/2013 12:28:00 ******/
CREATE NONCLUSTERED INDEX [IX_ASSET_SOURCE_ID] ON [dbo].[ENV_SOURCE_USAGE] 
(
	[ASSET_SOURCE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


