

/****** Object:  Index [IX_BMP_DB_CATEGORY_ID]    Script Date: 03/11/2013 12:01:30 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[BMP_DB]') AND name = N'IX_BMP_DB_CATEGORY_ID')
DROP INDEX [IX_BMP_DB_CATEGORY_ID] ON [dbo].[BMP_DB] WITH ( ONLINE = OFF )
GO



/****** Object:  Index [IX_BMP_DB_CATEGORY_ID]    Script Date: 03/11/2013 12:01:31 ******/
CREATE NONCLUSTERED INDEX [IX_BMP_DB_CATEGORY_ID] ON [dbo].[BMP_DB] 
(
	[BMP_DB_CATEGORY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


