IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CAP_USER_MODULE]') AND name = N'IX_CAP_USER_MODULE_manymany')
DROP INDEX [IX_CAP_USER_MODULE_manymany] ON [dbo].[CAP_USER_MODULE] WITH ( ONLINE = OFF )
GO

CREATE NONCLUSTERED INDEX [IX_CAP_USER_MODULE_manymany] ON [dbo].[CAP_USER_MODULE] 
(
	[User_ID] ASC,
	[Module_ID] ASC,
	[Client_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


