IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CAP_CLIENT_TYPE]') AND name = N'IX_CAP_CLIENT_TYPE_manymany')
DROP INDEX [IX_CAP_CLIENT_TYPE_manymany] ON [dbo].[CAP_CLIENT_TYPE] WITH ( ONLINE = OFF )
GO

CREATE NONCLUSTERED INDEX [IX_CAP_CLIENT_TYPE_manymany] ON [dbo].[CAP_CLIENT_TYPE] 
(
	[CLIENT_ID] ASC,
	[CLIENT_TYPE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


