

/****** Object:  Index [IX_CAP_CONTACT_STATUS_CD]    Script Date: 03/11/2013 12:17:02 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CAP_CONTACT]') AND name = N'IX_CAP_CONTACT_STATUS_CD')
DROP INDEX [IX_CAP_CONTACT_STATUS_CD] ON [dbo].[CAP_CONTACT] WITH ( ONLINE = OFF )
GO



/****** Object:  Index [IX_CAP_CONTACT_STATUS_CD]    Script Date: 03/11/2013 12:17:02 ******/
CREATE NONCLUSTERED INDEX [IX_CAP_CONTACT_STATUS_CD] ON [dbo].[CAP_CONTACT] 
(
	[STATUS_CD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


