

/****** Object:  Index [IX_ENV_SOURCE_SOURCE_TYPE_CD]    Script Date: 03/27/2013 11:51:57 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ENV_SOURCE]') AND name = N'IX_ENV_SOURCE_SOURCE_TYPE_CD')
DROP INDEX [IX_ENV_SOURCE_SOURCE_TYPE_CD] ON [dbo].[ENV_SOURCE] WITH ( ONLINE = OFF )
GO



/****** Object:  Index [IX_ENV_SOURCE_SOURCE_TYPE_CD]    Script Date: 03/27/2013 11:51:57 ******/
CREATE NONCLUSTERED INDEX [IX_ENV_SOURCE_SOURCE_TYPE_CD] ON [dbo].[ENV_SOURCE] 
(
	[SOURCE_TYPE_CD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


