IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ENV_SUBSTANCE_SCC_INFO]') AND name = N'IX_ENV_SUBSTANCE_SCC_INFO_manymany')
DROP INDEX [IX_ENV_SUBSTANCE_SCC_INFO_manymany] ON [dbo].[ENV_SUBSTANCE_SCC_INFO] WITH ( ONLINE = OFF )
GO

CREATE NONCLUSTERED INDEX [IX_ENV_SUBSTANCE_SCC_INFO_manymany] ON [dbo].[ENV_SUBSTANCE_SCC_INFO] 
(
	[SUBSTANCE_ID] ASC,
	[SCC_INFO_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


