

/****** Object:  Index [IX_ENV_SOURCE_USAGE_PERIOD_START_PERIOD_END]    Script Date: 03/27/2013 11:57:40 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ENV_SOURCE_USAGE]') AND name = N'IX_ENV_SOURCE_USAGE_PERIOD_START_PERIOD_END')
DROP INDEX [IX_ENV_SOURCE_USAGE_PERIOD_START_PERIOD_END] ON [dbo].[ENV_SOURCE_USAGE] WITH ( ONLINE = OFF )
GO



/****** Object:  Index [IX_ENV_SOURCE_USAGE_PERIOD_START_PERIOD_END]    Script Date: 03/27/2013 11:57:40 ******/
CREATE NONCLUSTERED INDEX [IX_ENV_SOURCE_USAGE_PERIOD_START_PERIOD_END] ON [dbo].[ENV_SOURCE_USAGE] 
(
	[PERIOD_START_TS] ASC,
	[PERIOD_END_TS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


