

/****** Object:  Index [IX_ENV_FACILITY_CLIENT_ID]    Script Date: 03/27/2013 11:38:56 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ENV_FACILITY]') AND name = N'IX_ENV_FACILITY_CLIENT_ID')
DROP INDEX [IX_ENV_FACILITY_CLIENT_ID] ON [dbo].[ENV_FACILITY] WITH ( ONLINE = OFF )
GO



/****** Object:  Index [IX_ENV_FACILITY_CLIENT_ID]    Script Date: 03/27/2013 11:38:56 ******/
CREATE NONCLUSTERED INDEX [IX_ENV_FACILITY_CLIENT_ID] ON [dbo].[ENV_FACILITY] 
(
	[CLIENT_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


