IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ENV_SUBSTANCE]') AND name = N'IX_ENV_SUBSTANCE_SUBSTANCE_TYPE_CD')
DROP INDEX [IX_ENV_SUBSTANCE_SUBSTANCE_TYPE_CD] ON [dbo].[ENV_SUBSTANCE] WITH ( ONLINE = OFF )
GO

CREATE NONCLUSTERED INDEX [IX_ENV_SUBSTANCE_SUBSTANCE_TYPE_CD] ON [dbo].[ENV_SUBSTANCE] 
(
	[SUBSTANCE_TYPE_CD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


