

/****** Object:  Index [IX_PROCESS_ASSET_PROCESS_ID]    Script Date: 03/27/2013 11:49:02 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ENV_PROCESS_ASSET]') AND name = N'IX_PROCESS_ASSET_PROCESS_ID')
DROP INDEX [IX_PROCESS_ASSET_PROCESS_ID] ON [dbo].[ENV_PROCESS_ASSET] WITH ( ONLINE = OFF )
GO



/****** Object:  Index [IX_PROCESS_ASSET_PROCESS_ID]    Script Date: 03/27/2013 11:49:02 ******/
CREATE NONCLUSTERED INDEX [IX_PROCESS_ASSET_PROCESS_ID] ON [dbo].[ENV_PROCESS_ASSET] 
(
	[PROCESS_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


