

/****** Object:  Index [IX_UNIT_OF_MEASURE_CD]    Script Date: 03/01/2013 12:29:58 ******/
CREATE NONCLUSTERED INDEX [IX_UNIT_OF_MEASURE_CD] ON [dbo].[ENV_SOURCE_USAGE] 
(
	[UNIT_OF_MEASURE_CD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


