INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#000000','Black','1')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#808080', 'Gray', '2')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#A9A9A9', 'Dark Gray', '3')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#D3D3D3', 'Light Gray', '4')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#FFFFFF', 'White', '5')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#7FFFD4', 'Aquamarine', '6')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#0000FF', 'Blue', '7')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#000080', 'Navy', '8')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#800080', 'Purple', '9')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#FF1493', 'Deep Pink', '10')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#EE82EE', 'Violet', '11')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#FFC0CB', 'Pink', '12')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#006400', 'Dark Green', '13')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#008000', 'Green', '14')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#9ACD32', 'Yellow Green', '15')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#FFFF00', 'Yellow', '16')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#FFA500', 'Orange', '17')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#FF0000', 'Red', '18')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#A52A2A', 'Brown', '19')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#DEB887', 'Burly Wood', '20')

INSERT INTO LOOKUP_ENV_DISPLAY_COLOR
(CODE, DESCRIPTION, ORDER_NUM)
VALUES ('#F5F5DC', 'Beige', '21')