ALTER TABLE [dbo].[EC_INSPECTION] ADD [TIME_HOUR] [int] NULL;
ALTER TABLE [dbo].[EC_INSPECTION] ADD [TIME_MINUTE] [int] NULL;
ALTER TABLE [dbo].[EC_INSPECTION] ADD [TIME_PERIOD] [varchar] (20) NULL;

