

ALTER TABLE ENV_SOURCE_SUBSTANCE
ADD [NG_EM_FACTOR] [decimal](18, 0) NULL;

ALTER TABLE ENV_SOURCE_SUBSTANCE
ADD [NG_EF_UNIT] [int] NULL;

ALTER TABLE ENV_SOURCE_SUBSTANCE
ADD [BL_EM_FACTOR] [decimal](18, 0) NULL;

ALTER TABLE ENV_SOURCE_SUBSTANCE
ADD [BL_EF_UNIT] [int] NULL;
