

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[FK_ENV_FACILITY_ENV_PERMIT_DETAIL]') and OBJECTPROPERTY(id, N'IsForeignKey') = 1)
ALTER TABLE [dbo].[ENV_FACILITY] DROP CONSTRAINT FK_ENV_FACILITY_ENV_PERMIT_DETAIL
GO



ALTER TABLE ENV_FACILITY DROP COLUMN PERMIT_DETAIL_ID