
-- ENV_SOURCE_SUBSTANCE

INSERT INTO ENV_UNIT_OF_MEASURE_MAP
(CLIENT_ID, TABLE_NAME, COLUMN_NAME, UM_CD)
VALUES
( 0, 'ENV_SOURCE_SUBSTANCE', 'NG_EF_UNIT', 8) --lbs/MmCf

INSERT INTO ENV_UNIT_OF_MEASURE_MAP
(CLIENT_ID, TABLE_NAME, COLUMN_NAME, UM_CD)
VALUES
( 0, 'ENV_SOURCE_SUBSTANCE', 'BL_EF_UNIT', 7) --lbs/1000 Gal


-- ENV_SOURCE_USAGE
INSERT INTO ENV_UNIT_OF_MEASURE_MAP
(CLIENT_ID, TABLE_NAME, COLUMN_NAME, UM_CD)
VALUES
( 0, 'ENV_SOURCE_USAGE', 'UNIT_OF_MEASURE_CD', 5) --MmCF
