

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ENV_CONTROL_USAGE_ENV_ASSET_SOURCE]') AND parent_object_id = OBJECT_ID(N'[dbo].[ENV_CONTROL_USAGE]'))
ALTER TABLE [dbo].[ENV_CONTROL_USAGE] DROP CONSTRAINT [FK_ENV_CONTROL_USAGE_ENV_ASSET_SOURCE]
GO



/****** Object:  Table [dbo].[ENV_CONTROL_USAGE]    Script Date: 02/04/2013 17:09:39 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ENV_CONTROL_USAGE]') AND type in (N'U'))
DROP TABLE [dbo].[ENV_CONTROL_USAGE]
GO


/****** Object:  Table [dbo].[ENV_CONTROL_USAGE]    Script Date: 02/04/2013 17:09:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ENV_CONTROL_USAGE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ASSET_EMITTED_SUBSTANCE_TYPE_ID] [int] NOT NULL,
	[PERIOD_START_TS] [datetime] NULL,
	[PERIOD_END_TS] [datetime] NULL,
	[DESCRIPTION] [varchar](200) NULL,
	[CREATE_TS] [datetime] NOT NULL,
	[UPDATE_TS] [datetime] NOT NULL,
	[UPDATE_USER_ID] [int] NOT NULL,
 CONSTRAINT [PK_ENV_CONTROL_USAGE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ENV_CONTROL_USAGE]  WITH CHECK ADD  CONSTRAINT [FK_ENV_CONTROL_USAGE_ENV_ASSET_SOURCE] FOREIGN KEY([ASSET_EMITTED_SUBSTANCE_TYPE_ID])
REFERENCES [dbo].[ENV_ASSET_EMITTED_SUBSTANCE_TYPE] ([ID])
GO

ALTER TABLE [dbo].[ENV_CONTROL_USAGE] CHECK CONSTRAINT [FK_ENV_CONTROL_USAGE_ENV_ASSET_SOURCE]
GO


