--Run each statement individually.

--INSERT TRIGGER
CREATE TRIGGER [tr_INS_AUDIT_ENV_ASSET_01] ON [dbo].[ENV_ASSET]
FOR INSERT
AS
INSERT INTO AUDIT_ENV_ASSET ([ASSET_ID], VERSION, PARENT_ASSET_ID,
	NAME, NUMBER, DESCRIPTION, CLIENT_ID, ACTIVE_TS, INACTIVE_TS, LOCATION,
	PERMIT_SHIELD, POINT, BUILDING_HEAT, PROCESS, METER, BELONGS_TO_METER,
	STATUS_CD, CREATE_TS, UPDATE_TS, UPDATE_USER_ID, AUDIT_REC_TYPE,
	AUDIT_DATE)
SELECT [ID], VERSION, PARENT_ASSET_ID,
	NAME, NUMBER, DESCRIPTION, CLIENT_ID, ACTIVE_TS, INACTIVE_TS, LOCATION,
	PERMIT_SHIELD, POINT, BUILDING_HEAT, PROCESS, METER, BELONGS_TO_METER,
	STATUS_CD, CREATE_TS, UPDATE_TS, UPDATE_USER_ID,'INSERT',GetDate()
FROM Inserted

------------------------------------------------------------------------------

-- DELETE TRIGGER
CREATE TRIGGER [tr_DEL_AUDIT_ENV_ASSET_01] ON [dbo].[ENV_ASSET]
FOR DELETE
AS
INSERT INTO AUDIT_ENV_ASSET ([ASSET_ID], VERSION, PARENT_ASSET_ID,
	NAME, NUMBER, DESCRIPTION, CLIENT_ID, ACTIVE_TS, INACTIVE_TS, LOCATION,
	PERMIT_SHIELD, POINT, BUILDING_HEAT, PROCESS, METER, BELONGS_TO_METER,
	STATUS_CD, CREATE_TS, UPDATE_TS, UPDATE_USER_ID, AUDIT_REC_TYPE,
	AUDIT_DATE)
SELECT [ID], VERSION, PARENT_ASSET_ID,
	NAME, NUMBER, DESCRIPTION, CLIENT_ID, ACTIVE_TS, INACTIVE_TS, LOCATION,
	PERMIT_SHIELD, POINT, BUILDING_HEAT, PROCESS, METER, BELONGS_TO_METER,
	STATUS_CD, CREATE_TS, UPDATE_TS, UPDATE_USER_ID,'DELETE',GetDate()
FROM DELETED

------------------------------------------------------------------------------
--UPDATE TRIGGER
CREATE TRIGGER [tr_UPD_AUDIT_ENV_ASSET_01] ON [dbo].[ENV_ASSET]
FOR UPDATE
AS
INSERT INTO AUDIT_ENV_ASSET ([ASSET_ID], VERSION, PARENT_ASSET_ID,
	NAME, NUMBER, DESCRIPTION, CLIENT_ID, ACTIVE_TS, INACTIVE_TS, LOCATION,
	PERMIT_SHIELD, POINT, BUILDING_HEAT, PROCESS, METER, BELONGS_TO_METER,
	STATUS_CD, CREATE_TS, UPDATE_TS, UPDATE_USER_ID, AUDIT_REC_TYPE,
	AUDIT_DATE)
SELECT [ID], VERSION, PARENT_ASSET_ID,
	NAME, NUMBER, DESCRIPTION, CLIENT_ID, ACTIVE_TS, INACTIVE_TS, LOCATION,
	PERMIT_SHIELD, POINT, BUILDING_HEAT, PROCESS, METER, BELONGS_TO_METER,
	STATUS_CD, CREATE_TS, UPDATE_TS, UPDATE_USER_ID,'UPDATE',GetDate()
FROM Inserted
