if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CAP_REPORT_ACCESS]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[CAP_REPORT_ACCESS]
GO

CREATE TABLE [dbo].[CAP_REPORT_ACCESS] (
	[ID] [int] IDENTITY (1, 1) NOT NULL ,
	[REPORT_ID] [int] NOT NULL ,
	[CLIENT_ID] [int] NOT NULL ,
	[ENABLED] [bit] NOT NULL 
) ON [PRIMARY]
GO



ALTER TABLE [dbo].[CAP_REPORT_ACCESS] WITH NOCHECK ADD 
	CONSTRAINT [PK_CAP_REPORT_ACCESS] PRIMARY KEY  CLUSTERED 
	(
		[ID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CAP_REPORT_ACCESS] ADD 
	CONSTRAINT [FK_CAP_REPORT_ACCESS_CAP_REPORT_OBJECT] FOREIGN KEY 
	(
		[REPORT_ID]
	) REFERENCES [dbo].[CAP_REPORT_OBJECT] (
		[ID]
	)
GO