
INSERT INTO [dbo].[CAP_REPORT_ACCESS] (REPORT_ID, CLIENT_ID, ENABLED)
VALUES (1, 682, 1);

INSERT INTO [dbo].[CAP_REPORT_ACCESS] (REPORT_ID, CLIENT_ID, ENABLED)
VALUES (2, 682, 1);

INSERT INTO [dbo].[CAP_REPORT_ACCESS] (REPORT_ID, CLIENT_ID, ENABLED)
VALUES (3, 682, 1);

INSERT INTO [dbo].[CAP_REPORT_ACCESS] (REPORT_ID, CLIENT_ID, ENABLED)
VALUES (4, 682, 1);

INSERT INTO [dbo].[CAP_REPORT_ACCESS] (REPORT_ID, CLIENT_ID, ENABLED)
VALUES (5, 682, 1);