--Run each statement individually.

--INSERT TRIGGER
CREATE TRIGGER [tr_INS_AUDIT_ENV_SOURCE_USAGE_01] ON [dbo].[ENV_SOURCE_USAGE]
FOR INSERT
AS
INSERT INTO AUDIT_ENV_SOURCE_USAGE ([SOURCE_USAGE_ID], VERSION, ASSET_SOURCE_ID, METER_READING,
	PERIOD_START_TS, PERIOD_END_TS, UNIT_OF_MEASURE_CD, CREATE_TS, UPDATE_TS,
	UPDATE_USER_ID, AUDIT_REC_TYPE, AUDIT_DATE)
SELECT [ID], VERSION, ASSET_SOURCE_ID, METER_READING,
	PERIOD_START_TS, PERIOD_END_TS, UNIT_OF_MEASURE_CD, CREATE_TS, UPDATE_TS,
	UPDATE_USER_ID,'INSERT',GetDate()
FROM Inserted

------------------------------------------------------------------------------

-- DELETE TRIGGER
CREATE TRIGGER [tr_DEL_AUDIT_ENV_SOURCE_USAGE_01] ON [dbo].[ENV_SOURCE_USAGE]
FOR DELETE
AS
INSERT INTO AUDIT_ENV_SOURCE_USAGE ([SOURCE_USAGE_ID], VERSION, ASSET_SOURCE_ID, METER_READING,
	PERIOD_START_TS, PERIOD_END_TS, UNIT_OF_MEASURE_CD, CREATE_TS, UPDATE_TS,
	UPDATE_USER_ID, AUDIT_REC_TYPE, AUDIT_DATE)
SELECT [ID], VERSION, ASSET_SOURCE_ID, METER_READING,
	PERIOD_START_TS, PERIOD_END_TS, UNIT_OF_MEASURE_CD, CREATE_TS, UPDATE_TS,
	UPDATE_USER_ID,'DELETE',GetDate()
FROM DELETED

------------------------------------------------------------------------------
--UPDATE TRIGGER
CREATE TRIGGER [tr_UPD_AUDIT_ENV_SOURCE_USAGE_01] ON [dbo].[ENV_SOURCE_USAGE]
FOR UPDATE
AS
INSERT INTO AUDIT_ENV_SOURCE_USAGE ([SOURCE_USAGE_ID], VERSION, ASSET_SOURCE_ID, METER_READING,
	PERIOD_START_TS, PERIOD_END_TS, UNIT_OF_MEASURE_CD, CREATE_TS, UPDATE_TS,
	UPDATE_USER_ID, AUDIT_REC_TYPE, AUDIT_DATE)
SELECT [ID], VERSION, ASSET_SOURCE_ID, METER_READING,
	PERIOD_START_TS, PERIOD_END_TS, UNIT_OF_MEASURE_CD, CREATE_TS, UPDATE_TS,
	UPDATE_USER_ID,'UPDATE',GetDate()
FROM Inserted
