--Run each statement individually.

--INSERT TRIGGER
CREATE TRIGGER [tr_INS_AUDIT_ENV_SOURCE_01] ON [dbo].[ENV_SOURCE]
FOR INSERT
AS
INSERT INTO AUDIT_ENV_SOURCE ([SOURCE_ID], VERSION, DISPLAY_NAME, CLIENT_ID, PART_NUMBER,
	BATCH_NUMBER, DESCRIPTION, LBS_VOC, LBS_VOC_UM, DENSITY, DENSITY_UM,
	LBS_HAPS, LBS_HAPS_UM, PCT_SOLIDS_VOLUME, PCT_SOLIDS_WEIGHT, INFO_ORIGIN,
	SOURCE_TYPE_CD, STATUS_CD, CREATE_TS, UPDATE_TS, UPDATE_USER_ID,
	DISPLAY_COLOR_CD, HC_FUEL, AUDIT_REC_TYPE, AUDIT_DATE)
SELECT [ID], VERSION, DISPLAY_NAME, CLIENT_ID, PART_NUMBER,
	BATCH_NUMBER, DESCRIPTION, LBS_VOC, LBS_VOC_UM, DENSITY, DENSITY_UM,
	LBS_HAPS, LBS_HAPS_UM, PCT_SOLIDS_VOLUME, PCT_SOLIDS_WEIGHT, INFO_ORIGIN,
	SOURCE_TYPE_CD, STATUS_CD, CREATE_TS, UPDATE_TS, UPDATE_USER_ID,
	DISPLAY_COLOR_CD, HC_FUEL,'INSERT',GetDate()
FROM Inserted

------------------------------------------------------------------------------

-- DELETE TRIGGER
CREATE TRIGGER [tr_DEL_AUDIT_ENV_SOURCE_01] ON [dbo].[ENV_SOURCE]
FOR DELETE
AS
INSERT INTO AUDIT_ENV_SOURCE ([SOURCE_ID], VERSION, DISPLAY_NAME, CLIENT_ID, PART_NUMBER,
	BATCH_NUMBER, DESCRIPTION, LBS_VOC, LBS_VOC_UM, DENSITY, DENSITY_UM,
	LBS_HAPS, LBS_HAPS_UM, PCT_SOLIDS_VOLUME, PCT_SOLIDS_WEIGHT, INFO_ORIGIN,
	SOURCE_TYPE_CD, STATUS_CD, CREATE_TS, UPDATE_TS, UPDATE_USER_ID,
	DISPLAY_COLOR_CD, HC_FUEL, AUDIT_REC_TYPE, AUDIT_DATE)
SELECT [ID], VERSION, DISPLAY_NAME, CLIENT_ID, PART_NUMBER,
	BATCH_NUMBER, DESCRIPTION, LBS_VOC, LBS_VOC_UM, DENSITY, DENSITY_UM,
	LBS_HAPS, LBS_HAPS_UM, PCT_SOLIDS_VOLUME, PCT_SOLIDS_WEIGHT, INFO_ORIGIN,
	SOURCE_TYPE_CD, STATUS_CD, CREATE_TS, UPDATE_TS, UPDATE_USER_ID,
	DISPLAY_COLOR_CD, HC_FUEL,'DELETE',GetDate()
FROM DELETED

------------------------------------------------------------------------------
--UPDATE TRIGGER
CREATE TRIGGER [tr_UPD_AUDIT_ENV_SOURCE_01] ON [dbo].[ENV_SOURCE]
FOR UPDATE
AS
INSERT INTO AUDIT_ENV_SOURCE ([SOURCE_ID], VERSION, DISPLAY_NAME, CLIENT_ID, PART_NUMBER,
	BATCH_NUMBER, DESCRIPTION, LBS_VOC, LBS_VOC_UM, DENSITY, DENSITY_UM,
	LBS_HAPS, LBS_HAPS_UM, PCT_SOLIDS_VOLUME, PCT_SOLIDS_WEIGHT, INFO_ORIGIN,
	SOURCE_TYPE_CD, STATUS_CD, CREATE_TS, UPDATE_TS, UPDATE_USER_ID,
	DISPLAY_COLOR_CD, HC_FUEL, AUDIT_REC_TYPE, AUDIT_DATE)
SELECT [ID], VERSION, DISPLAY_NAME, CLIENT_ID, PART_NUMBER,
	BATCH_NUMBER, DESCRIPTION, LBS_VOC, LBS_VOC_UM, DENSITY, DENSITY_UM,
	LBS_HAPS, LBS_HAPS_UM, PCT_SOLIDS_VOLUME, PCT_SOLIDS_WEIGHT, INFO_ORIGIN,
	SOURCE_TYPE_CD, STATUS_CD, CREATE_TS, UPDATE_TS, UPDATE_USER_ID,
	DISPLAY_COLOR_CD, HC_FUEL,'UPDATE',GetDate()
FROM Inserted
