--Run each statement individually.

--INSERT TRIGGER
CREATE TRIGGER [tr_INS_AUDIT_ENV_SUBSTANCE_01] ON [dbo].[ENV_SUBSTANCE]
FOR INSERT
AS
INSERT INTO AUDIT_ENV_SUBSTANCE ([SUBSTANCE_ID], VERSION, NAME, PART_NUM,
	SUBSTANCE_TYPE_CD, CLIENT_ID, STATUS_CD, CREATE_TS, UPDATE_TS,
	UPDATE_USER_ID, AUDIT_REC_TYPE, AUDIT_DATE) 
SELECT [ID], VERSION, NAME, PART_NUM,
	SUBSTANCE_TYPE_CD, CLIENT_ID, STATUS_CD, CREATE_TS, UPDATE_TS,
	UPDATE_USER_ID,'INSERT',GetDate()
FROM Inserted

------------------------------------------------------------------------------

-- DELETE TRIGGER
CREATE TRIGGER [tr_DEL_AUDIT_ENV_SUBSTANCE_01] ON [dbo].[ENV_SUBSTANCE]
FOR DELETE
AS
INSERT INTO AUDIT_ENV_SUBSTANCE ([SUBSTANCE_ID], VERSION, NAME, PART_NUM,
	SUBSTANCE_TYPE_CD, CLIENT_ID, STATUS_CD, CREATE_TS, UPDATE_TS,
	UPDATE_USER_ID, AUDIT_REC_TYPE, AUDIT_DATE) 
SELECT [ID], VERSION, NAME, PART_NUM,
	SUBSTANCE_TYPE_CD, CLIENT_ID, STATUS_CD, CREATE_TS, UPDATE_TS,
	UPDATE_USER_ID,'DELETE',GetDate()
FROM DELETED

------------------------------------------------------------------------------
--UPDATE TRIGGER
CREATE TRIGGER [tr_UPD_AUDIT_ENV_SUBSTANCE_01] ON [dbo].[ENV_SUBSTANCE]
FOR UPDATE
AS
INSERT INTO AUDIT_ENV_SUBSTANCE ([SUBSTANCE_ID], VERSION, NAME, PART_NUM,
	SUBSTANCE_TYPE_CD, CLIENT_ID, STATUS_CD, CREATE_TS, UPDATE_TS,
	UPDATE_USER_ID, AUDIT_REC_TYPE, AUDIT_DATE) 
SELECT [ID], VERSION, NAME, PART_NUM,
	SUBSTANCE_TYPE_CD, CLIENT_ID, STATUS_CD, CREATE_TS, UPDATE_TS,
	UPDATE_USER_ID,'UPDATE',GetDate()
FROM Inserted
