-- UPDATE TRIGGER
USE cap2
GO

if exists (select * from dbo.sysobjects where name = 'tr_UPD_AUDIT_EC_INSPECTION_01')
DROP TRIGGER tr_UPD_AUDIT_EC_INSPECTION_01
GO

if exists (select * from dbo.sysobjects where name =  'tr_DEL_Audit_EC_INSPECTION_01')
DROP TRIGGER tr_DEL_AUDIT_EC_INSPECTION_01
GO

if exists (select * from dbo.sysobjects where name =  'tr_INS_Audit_EC_INSPECTION_01')
DROP TRIGGER tr_INS_AUDIT_EC_INSPECTION_01
GO


CREATE TRIGGER [tr_UPD_AUDIT_EC_INSPECTION_01] ON [dbo].[EC_INSPECTION]
FOR UPDATE
AS
INSERT INTO AUDIT_EC_INSPECTION ([ID], VERSION, PROJECT_ID, CLIENT_ID, INSPECTION_DATE, ENTERED_DATE,
	WEATHER_TRENDS, TEMPERATURE, COMMENT, PRECIP_END_DATE, PRECIP_AMOUNT, PRECIP_SOURCE, 
	INSPECTION_ACTION_COMMENT, INSPECTION_ACTION_ID, INSPECTION_REASON_ID, CREATE_TS,
	UPDATE_TS, UPDATE_USER_ID, STATUS_CD, AUDIT_REC_TYPE, AUDIT_DATE)

SELECT [ID], VERSION, PROJECT_ID, CLIENT_ID, INSPECTION_DATE, ENTERED_DATE,
	WEATHER_TRENDS, TEMPERATURE, COMMENT, PRECIP_END_DATE, PRECIP_AMOUNT, PRECIP_SOURCE, 
	INSPECTION_ACTION_COMMENT, INSPECTION_ACTION_ID, INSPECTION_REASON_ID, CREATE_TS,
	UPDATE_TS, UPDATE_USER_ID, STATUS_CD,'UPDATE',GetDate()
FROM Inserted
GO
----------------------------------
-- DELETE TRIGGER

CREATE TRIGGER [tr_DEL_AUDIT_EC_INSPECTION_01] ON [dbo].[EC_INSPECTION]
FOR DELETE
AS
INSERT INTO AUDIT_EC_INSPECTION ([ID], VERSION, PROJECT_ID, CLIENT_ID, INSPECTION_DATE, ENTERED_DATE,
	WEATHER_TRENDS, TEMPERATURE, COMMENT, PRECIP_END_DATE, PRECIP_AMOUNT, PRECIP_SOURCE, 
	INSPECTION_ACTION_COMMENT, INSPECTION_ACTION_ID, INSPECTION_REASON_ID, CREATE_TS,
	UPDATE_TS, UPDATE_USER_ID, STATUS_CD, AUDIT_REC_TYPE, AUDIT_DATE)

SELECT [ID], VERSION, PROJECT_ID, CLIENT_ID, INSPECTION_DATE, ENTERED_DATE,
	WEATHER_TRENDS, TEMPERATURE, COMMENT, PRECIP_END_DATE, PRECIP_AMOUNT, PRECIP_SOURCE, 
	INSPECTION_ACTION_COMMENT, INSPECTION_ACTION_ID, INSPECTION_REASON_ID, CREATE_TS,
	UPDATE_TS, UPDATE_USER_ID, STATUS_CD,'DELETE',GetDate()
FROM DELETED
GO
-----------------------------------
--INSERT TRIGGER

CREATE TRIGGER [tr_INS_AUDIT_EC_INSPECTION_01] ON [dbo].[EC_INSPECTION]
FOR INSERT
AS
INSERT INTO AUDIT_EC_INSPECTION ([ID], VERSION, PROJECT_ID, CLIENT_ID, INSPECTION_DATE, ENTERED_DATE,
	WEATHER_TRENDS, TEMPERATURE, COMMENT, PRECIP_END_DATE, PRECIP_AMOUNT, PRECIP_SOURCE, 
	INSPECTION_ACTION_COMMENT, INSPECTION_ACTION_ID, INSPECTION_REASON_ID, CREATE_TS,
	UPDATE_TS, UPDATE_USER_ID, STATUS_CD, AUDIT_REC_TYPE, AUDIT_DATE)

SELECT [ID], VERSION, PROJECT_ID, CLIENT_ID, INSPECTION_DATE, ENTERED_DATE,
	WEATHER_TRENDS, TEMPERATURE, COMMENT, PRECIP_END_DATE, PRECIP_AMOUNT, PRECIP_SOURCE, 
	INSPECTION_ACTION_COMMENT, INSPECTION_ACTION_ID, INSPECTION_REASON_ID, CREATE_TS,
	UPDATE_TS, UPDATE_USER_ID, STATUS_CD,'INSERT',GetDate()
FROM Inserted
GO