
ALTER TABLE EC_PROJECT
ADD [RFA_NUMBER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL

ALTER TABLE EC_PROJECT
ADD [BLOCK_NUMBER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL

ALTER TABLE EC_PROJECT
ADD [LOT_NUMBER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL