if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[FK_ENV_SOURCE_SUBSTANCE_LOOKUP_ENV_UNIT_OF_MEASURE]') 
and OBJECTPROPERTY(id, N'IsForeignKey') = 1)
ALTER TABLE [dbo].[ENV_SOURCE_SUBSTANCE] DROP CONSTRAINT FK_ENV_SOURCE_SUBSTANCE_LOOKUP_ENV_UNIT_OF_MEASURE
GO



ALTER TABLE ENV_SOURCE_SUBSTANCE
DROP COLUMN UNIT_OF_MEASURE_CD

