if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[FK_ENV_ASSET_ATTR_LOOKUP_ENV_UNIT_OF_MEASURE]') 
and OBJECTPROPERTY(id, N'IsForeignKey') = 1)
ALTER TABLE [dbo].[ENV_ASSET_ATTR] DROP CONSTRAINT FK_ENV_ASSET_ATTR_LOOKUP_ENV_UNIT_OF_MEASURE
GO



ALTER TABLE ENV_ASSET_ATTR
DROP COLUMN EP_UNIT_OF_MEASURE_CD